// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  biography: dynamic(() => import("./Biography")),
  content_index: dynamic(() => import("./ContentIndex")),
  gallery: dynamic(() => import("./Gallery")),
  heading: dynamic(() => import("./Heading")),
  hero: dynamic(() => import("./Hero")),
  image_block: dynamic(() => import("./ImageBlock")),
  text_block: dynamic(() => import("./TextBlock")),
};
